# Generated by nim_native_dynlib; do not edit.

import std/tables

const nativeLibrary* = "/Volumes/projects/nims/binny/examples/nim_native_dynlib/nimcache/libproducer.dylib"

type
  Vec2* = object
    x*: float32
    y*: float32

  Child* = ref object
    label*: string

  Renderer* = ref object
    name*: string
    size*: Vec2
    child*: Child

  Hooked* = object
    value*: int

  MoveOnly* = object
    value*: int

  PayloadKind* = enum
    pkCode = 0
    pkText = 1

  Payload* = object
    case kind*: PayloadKind
    of pkCode:
      code*: int
    of pkText:
      text*: string

  Base* {.inheritable.} = object
    baseValue*: int

  Derived* = object of Base
    detail*: string

  Packed* {.packed.} = object
    small*: uint8
    large*: uint32

  NumberSpan* = object
    value*: int

  Number* = int16

  RenderList* = seq[string]

  Renders* = ref object
    layers*: OrderedTable[Number, RenderList]

  ImportedValue* = object
    label*: string

  NativeAbit18_181_pro47ngcy1* = tuple
    Field0: NumberSpan
    Field1: string

static:
  doAssert sizeof(Vec2) == 8
  doAssert alignof(Vec2) == 4
  doAssert offsetOf(Vec2, x) == 0
  doAssert offsetOf(Vec2, y) == 4
  doAssert sizeof(Child) == 8
  doAssert alignof(Child) == 8
  doAssert sizeof(Renderer) == 8
  doAssert alignof(Renderer) == 8
  doAssert sizeof(Hooked) == 8
  doAssert alignof(Hooked) == 8
  doAssert offsetOf(Hooked, value) == 0
  doAssert sizeof(MoveOnly) == 8
  doAssert alignof(MoveOnly) == 8
  doAssert offsetOf(MoveOnly, value) == 0
  doAssert sizeof(PayloadKind) == 1
  doAssert alignof(PayloadKind) == 1
  doAssert sizeof(Payload) == 24
  doAssert alignof(Payload) == 8
  doAssert offsetOf(Payload, kind) == 0
  doAssert offsetOf(Payload, code) == 8
  doAssert offsetOf(Payload, text) == 8
  doAssert sizeof(Base) == 16
  doAssert alignof(Base) == 8
  doAssert offsetOf(Base, baseValue) == 8
  doAssert sizeof(Derived) == 32
  doAssert alignof(Derived) == 8
  doAssert offsetOf(Derived, detail) == 16
  doAssert sizeof(Packed) == 5
  doAssert alignof(Packed) == 1
  doAssert offsetOf(Packed, small) == 0
  doAssert offsetOf(Packed, large) == 1
  doAssert sizeof(NumberSpan) == 8
  doAssert alignof(NumberSpan) == 8
  doAssert offsetOf(NumberSpan, value) == 0
  doAssert sizeof(Number) == 2
  doAssert alignof(Number) == 2
  doAssert sizeof(RenderList) == 16
  doAssert alignof(RenderList) == 8
  doAssert sizeof(Renders) == 8
  doAssert alignof(Renders) == 8
  doAssert sizeof(ImportedValue) == 16
  doAssert alignof(ImportedValue) == 8
  doAssert offsetOf(ImportedValue, label) == 0

proc nativeNimMain() {.cdecl, importc: "NimMain", dynlib: nativeLibrary.}

nativeNimMain()

{.push nimcall, dynlib: nativeLibrary.}

proc `=destroy`(hooked: Hooked) {.importc: "eqdestroy__u0__producer".}

proc `=copy`(dest: var Hooked; source: Hooked) {.importc: "eqcopy__u0__producer".}

proc `=destroy`(moveOnly: MoveOnly) {.importc: "eqdestroy__u1__producer".}

proc `=copy`(dest: var MoveOnly; source: MoveOnly) {.error.}

proc newRenderer*(name: string): Renderer {.importc: "newRenderer_u0__producer".}

proc translate*(renderer: Renderer; delta: Vec2) {.importc: "translate_u0__producer".}

proc describe*(renderer: Renderer): string {.importc: "describe_u0__producer".}

proc message*(): string {.importc: "message_u0__producer".}

proc sumNumbers*(numbers: openArray[int]): int {.importc: "sumNumbers_u0__producer".}

proc sumSpans*(spans: openArray[NumberSpan]): int {.importc: "sumSpans_u0__producer".}

proc sumLabeledSpans*(spans: openArray[NativeAbit18_181_pro47ngcy1]): int {.importc: "sumLabeledSpans_u0__producer".}

proc doubleNumber*(number: Number): Number {.importc: "doubleNumber_u0__producer".}

proc newRenders*(): Renders {.importc: "newRenders_u0__producer".}

proc newTextPayload*(text: string): Payload {.importc: "newTextPayload_u0__producer".}

proc payloadDescription*(payload: Payload): string {.importc: "payloadDescription_u0__producer".}

proc newDerived*(value: int; detail: string): Derived {.importc: "newDerived_u0__producer".}

proc derivedDescription*(value: Derived): string {.importc: "derivedDescription_u0__producer".}

proc newPacked*(small: uint8; large: uint32): Packed {.importc: "newPacked_u0__producer".}

proc newHooked*(value: int): Hooked {.importc: "newHooked_u0__producer".}

proc hookedCopyCount*(): int {.importc: "hookedCopyCount_u0__producer".}

proc hookedDestroyCount*(): int {.importc: "hookedDestroyCount_u0__producer".}

proc newMoveOnly*(value: int): MoveOnly {.importc: "newMoveOnly_u0__producer".}

proc newImportedValue*(label: string): ImportedValue {.importc: "newImportedValue_u0__sup74asby1".}

proc importedLabel*(value: ImportedValue): string {.importc: "importedLabel_u0__sup74asby1".}

{.pop.}
